[package]
name = "nova-registro"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }

[features]
banco = ["dep:serde", "dep:serde_json"]

[[bin]]
name = "banco-registro"
path = "src/banco.rs"
required-features = ["banco"]
